// Oh! You Fancy Focaccia — the website and its order book.
//
// The pages under public/ are generated by `npm run build:site`. This server
// serves them, takes orders from the Order page, and runs the admin that
// Amanda works from. Everything that needs the database lives under /api and
// /admin; the rest of the site keeps working without one.
const path = require('path');
const crypto = require('crypto');
const express = require('express');
const helmet = require('helmet');
const compression = require('compression');
const rateLimit = require('express-rate-limit');
const db = require('./db');
const mail = require('./mail');

const app = express();
const PORT = process.env.PORT || 3000;
const PUBLIC_DIR = path.join(__dirname, 'public');

app.disable('x-powered-by');
app.set('trust proxy', 1);

// Absolute origin for links that leave the server — the "review & respond"
// button in the order email. Railway injects RAILWAY_PUBLIC_DOMAIN on every
// deploy, so a forgotten BASE_URL still yields a reachable origin.
function resolveBaseUrl(env = process.env, port = PORT) {
  if (env.BASE_URL) return env.BASE_URL.replace(/\/$/, '');
  if (env.CANONICAL_HOST) return `https://${env.CANONICAL_HOST}`;
  if (env.RAILWAY_PUBLIC_DOMAIN) return `https://${env.RAILWAY_PUBLIC_DOMAIN}`;
  return `http://localhost:${port}`;
}
const BASE_URL = resolveBaseUrl();

// Market days, as the day-of-week numbers Date#getDay uses.
const MARKET_DAYS = [3, 6];
const FULFILLMENTS = ['pickup', 'delivery', 'shipping'];
const ORDER_STATUSES = ['pending', 'accepted', 'declined', 'cancelled', 'completed'];
const PAYMENT_STATUSES = ['unpaid', 'deposit_paid', 'paid', 'refunded'];
const MAX_QTY = 50;

// The design leans on inline style attributes throughout, so style-src has to
// allow them; scripts do not, which is why every script is its own file.
app.use(helmet({
  contentSecurityPolicy: {
    directives: {
      defaultSrc: ["'self'"],
      scriptSrc: ["'self'"],
      styleSrc: ["'self'", "'unsafe-inline'", 'https://fonts.googleapis.com'],
      fontSrc: ["'self'", 'https://fonts.gstatic.com'],
      imgSrc: ["'self'", 'data:'],
      connectSrc: ["'self'"],
      formAction: ["'self'"],
      frameAncestors: ["'none'"],
      objectSrc: ["'none'"],
      baseUri: ["'self'"],
      upgradeInsecureRequests: [],
    },
  },
  crossOriginEmbedderPolicy: false,
  referrerPolicy: { policy: 'strict-origin-when-cross-origin' },
}));
app.use(compression());
app.use(express.json({ limit: '64kb' }));

const CANONICAL_HOST = process.env.CANONICAL_HOST;
if (CANONICAL_HOST) {
  app.use((req, res, next) => {
    const host = (req.headers.host || '').toLowerCase().split(':')[0];
    if (host && host !== CANONICAL_HOST && !host.endsWith('.up.railway.app')) {
      return res.redirect(308, `https://${CANONICAL_HOST}${req.originalUrl}`);
    }
    next();
  });
}

app.get('/healthz', (_req, res) => res.status(200).send('ok'));
app.get('/readyz', asyncHandler(async (_req, res) => {
  if (!process.env.DATABASE_URL) return res.status(503).json({ ok: false, reason: 'database_not_configured' });
  try {
    await db.pool.query('SELECT 1');
    return res.json({ ok: true, emailConfigured: mail.configured() });
  } catch (_err) {
    return res.status(503).json({ ok: false, reason: 'database_unavailable' });
  }
}));

// ── helpers ──────────────────────────────────────────────────────────────
function asyncHandler(fn) {
  return (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
}

async function deliverOutbox(row) {
  try {
    const result = await mail.send({
      to: row.recipient, replyTo: row.reply_to,
      subject: row.subject, html: row.html,
    });
    if (result.sent) await db.markEmailSent(row.id);
    else await db.markEmailFailed(row.id, result.reason);
    return result;
  } catch (err) {
    await db.markEmailFailed(row.id, err.message);
    return { sent: false, reason: err.message };
  }
}

async function queueAndDeliver({ orderId = null, kind, to, replyTo, subject, html }) {
  const row = await db.queueEmail({ orderId, kind, to, replyTo, subject, html });
  return deliverOutbox(row);
}

async function processEmailOutbox() {
  const rows = await db.claimDueEmails(10);
  await Promise.all(rows.map((row) => deliverOutbox(row)));
  return rows.length;
}
const str = (v) => (typeof v === 'string' ? v.trim() : '');
const isEmail = (v) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);
function isIsoDate(v) {
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(String(v));
  if (!match) return false;
  const year = Number(match[1]), month = Number(match[2]), day = Number(match[3]);
  if (year < 1 || month < 1 || month > 12 || day < 1) return false;
  return day <= new Date(Date.UTC(year, month, 0)).getUTCDate();
}

function safeEqual(a, b) {
  const ha = crypto.createHash('sha256').update(String(a ?? '')).digest();
  const hb = crypto.createHash('sha256').update(String(b ?? '')).digest();
  return crypto.timingSafeEqual(ha, hb);
}
function hashPassword(password) {
  const salt = crypto.randomBytes(16).toString('hex');
  return `${salt}:${crypto.scryptSync(password, salt, 64).toString('hex')}`;
}
function verifyPassword(password, stored) {
  const [salt, hash] = String(stored ?? '').split(':');
  if (!salt || !hash) return false;
  const a = Buffer.from(hash, 'hex');
  const b = crypto.scryptSync(password, salt, 64);
  return a.length === b.length && crypto.timingSafeEqual(a, b);
}

// Use UTC for the business date so the API and browser calendar agree across
// time zones. The configured notice window is the actual number of days.
function minDateIso(noticeDays) {
  const d = new Date();
  d.setUTCHours(0, 0, 0, 0);
  d.setUTCDate(d.getUTCDate() + Math.max(0, noticeDays));
  return db.toIsoDate(d);
}
function isMarketDay(iso) {
  return MARKET_DAYS.includes(new Date(`${iso}T00:00:00`).getDay());
}

// ── sessions ─────────────────────────────────────────────────────────────
// Signed with the stored password hash as the HMAC key: no new secret to
// configure, survives restarts, and changing the password re-keys every
// session, so all of them are invalidated for free.
const SESSION_COOKIE = 'oyff_admin';
const SESSION_TTL_MS = 12 * 60 * 60 * 1000;

function readCookie(req, name) {
  const raw = req.headers.cookie;
  if (!raw) return null;
  for (const part of raw.split(';')) {
    const eq = part.indexOf('=');
    if (eq === -1 || part.slice(0, eq).trim() !== name) continue;
    try { return decodeURIComponent(part.slice(eq + 1).trim()); } catch { return null; }
  }
  return null;
}
function signSession(payload, key) {
  const body = Buffer.from(JSON.stringify(payload)).toString('base64url');
  return `${body}.${crypto.createHmac('sha256', key).update(body).digest('base64url')}`;
}
function verifySession(token, key) {
  if (typeof token !== 'string') return null;
  const dot = token.lastIndexOf('.');
  if (dot < 1) return null;
  const body = token.slice(0, dot);
  const mac = Buffer.from(token.slice(dot + 1));
  const expected = Buffer.from(crypto.createHmac('sha256', key).update(body).digest('base64url'));
  if (mac.length !== expected.length || !crypto.timingSafeEqual(mac, expected)) return null;
  let payload;
  try { payload = JSON.parse(Buffer.from(body, 'base64url').toString()); } catch { return null; }
  if (!payload || typeof payload.exp !== 'number' || Date.now() >= payload.exp) return null;
  return payload;
}
function issueSession(req, res, username, key) {
  res.cookie(SESSION_COOKIE, signSession({ u: username, exp: Date.now() + SESSION_TTL_MS }, key), {
    httpOnly: true, sameSite: 'strict', secure: req.secure, maxAge: SESSION_TTL_MS, path: '/',
  });
}
function wantsHtmlPage(req) {
  return req.method === 'GET' && (req.get('accept') || '').includes('text/html');
}

// Credentials live in the database so the password can be changed from the
// admin. Before any row exists, ADMIN_USERNAME / ADMIN_PASSWORD from the
// environment are the credentials, and the first successful sign-in stores a
// hash of them.
async function checkLogin(username, password) {
  const creds = await db.getAdminCredentials();
  if (creds) {
    if (safeEqual(username, creds.username) && verifyPassword(password, creds.password_hash)) return creds;
    return null;
  }
  const u = process.env.ADMIN_USERNAME, p = process.env.ADMIN_PASSWORD;
  if (!u || !p) return { unconfigured: true };
  if (safeEqual(username, u) && safeEqual(password, p)) {
    const password_hash = hashPassword(p);
    await db.setAdminCredentials(u, password_hash);
    return { username: u, password_hash };
  }
  return null;
}

async function adminAuth(req, res, next) {
  try {
    const creds = await db.getAdminCredentials();
    const token = readCookie(req, SESSION_COOKIE);
    if (creds && token && verifySession(token, creds.password_hash)) return next();
  } catch (err) {
    return next(err);
  }
  if (wantsHtmlPage(req)) return res.redirect(302, '/admin/login');
  return res.status(401).json({ error: 'Sign in to continue.' });
}

// ── rate limits ──────────────────────────────────────────────────────────
const apiLimiter = rateLimit({
  windowMs: 15 * 60 * 1000, limit: Number(process.env.API_RATE_LIMIT) || 300,
  standardHeaders: true, legacyHeaders: false,
});
const writeLimiter = rateLimit({
  windowMs: 15 * 60 * 1000, limit: Number(process.env.WRITE_RATE_LIMIT) || 8,
  standardHeaders: true, legacyHeaders: false,
  message: { error: 'Too many requests. Please try again in a little while.' },
});
const loginLimiter = rateLimit({
  windowMs: 15 * 60 * 1000, limit: Number(process.env.LOGIN_RATE_LIMIT) || 10,
  skipSuccessfulRequests: true, standardHeaders: true, legacyHeaders: false,
  message: { error: 'Too many sign-in attempts. Please try again later.' },
});

// Without a database there is no order book. The pages still serve; the
// order form and the admin say so plainly instead of throwing.
app.use(['/api', '/admin', '/respond'], (req, res, next) => {
  if (process.env.DATABASE_URL) return next();
  if (wantsHtmlPage(req)) return res.status(503).send('Ordering is not set up yet.');
  res.status(503).json({ error: 'Ordering is not set up yet. Please email us instead.' });
});
app.use(['/api', '/respond'], apiLimiter);

// ── admin sign-in ────────────────────────────────────────────────────────
app.get('/admin/login', (_req, res) => res.sendFile(path.join(PUBLIC_DIR, 'admin-login.html')));

app.post('/admin/login', loginLimiter, asyncHandler(async (req, res) => {
  const result = await checkLogin(str(req.body?.username), String(req.body?.password ?? ''));
  if (result?.unconfigured) return res.status(500).json({ error: 'Admin sign-in is not configured.' });
  if (!result) return res.status(401).json({ error: 'Incorrect username or password.' });
  issueSession(req, res, result.username, result.password_hash);
  res.json({ ok: true });
}));

app.post('/admin/logout', (_req, res) => {
  res.clearCookie(SESSION_COOKIE, { path: '/' });
  res.status(204).end();
});

app.use(['/admin', '/admin.html', '/api/admin'], adminAuth);
app.get('/admin', (_req, res) => res.sendFile(path.join(PUBLIC_DIR, 'admin.html')));

// ── public API ───────────────────────────────────────────────────────────
app.get('/api/menu', asyncHandler(async (_req, res) => {
  const [items, settings] = await Promise.all([db.listMenu({ availableOnly: true }), db.getSettings()]);
  res.json({
    courses: db.COURSES,
    items: items.map((m) => ({ id: m.id, course: m.course, name: m.name, description: m.description, price: m.price, image: m.image })),
    paymentInstructions: settings.payment_instructions,
  });
}));

app.get('/api/availability', asyncHandler(async (_req, res) => {
  const [blocked, settings] = await Promise.all([db.getBlockedRanges(), db.getSettings()]);
  res.json({
    minNoticeDays: Number(settings.min_notice_days) || 0,
    marketDays: MARKET_DAYS,
    pickupNote: settings.pickup_note,
    blocked: blocked.map(({ start, end }) => ({ start, end })),
  });
}));

// Checks the parts of an order that are the same whether it came from the
// website or was typed in by Amanda. Returns { error } or { order, items }.
async function prepareOrder(body, { website }) {
  const order = {
    firstName: str(body.firstName), lastName: str(body.lastName),
    email: str(body.email).toLowerCase(), phone: str(body.phone),
    fulfillment: str(body.fulfillment) || 'pickup', neededDate: str(body.neededDate),
    address: str(body.address), notes: str(body.notes),
  };
  if (!order.firstName || !order.lastName) return { error: 'Please tell us your first and last name.' };
  if (website && !order.email) return { error: 'Please enter an email address so we can confirm your order.' };
  if (!order.email && !order.phone) return { error: 'An email address or phone number is required.' };
  if (order.email && !isEmail(order.email)) return { error: 'That email address does not look right.' };
  if (!FULFILLMENTS.includes(order.fulfillment)) return { error: 'Choose pickup, delivery or shipping.' };
  if (order.fulfillment !== 'pickup' && !order.address) return { error: 'Please give us an address for delivery or shipping.' };
  if (!isIsoDate(order.neededDate)) return { error: 'Please choose a date.' };
  if (order.notes.length > 2000) return { error: 'Notes are limited to 2000 characters.' };

  const requested = Array.isArray(body.items) ? body.items : [];
  if (!requested.length) return { error: 'Add at least one item to your order.' };
  const wanted = new Map();
  for (const it of requested) {
    const id = Number(it?.id), qty = Number(it?.quantity);
    if (!Number.isInteger(id) || !Number.isInteger(qty) || qty < 1 || qty > MAX_QTY) {
      return { error: `Quantities must be whole numbers between 1 and ${MAX_QTY}.` };
    }
    const total = (wanted.get(id) || 0) + qty;
    if (total > MAX_QTY) return { error: `Quantities must be whole numbers between 1 and ${MAX_QTY}.` };
    wanted.set(id, total);
  }
  const menu = await db.getMenuItems([...wanted.keys()]);
  const byId = new Map(menu.map((m) => [m.id, m]));
  const items = [];
  for (const [id, quantity] of wanted) {
    const m = byId.get(id);
    if (!m || (website && !m.available)) return { error: 'One of those items is not available right now. Please refresh the menu.' };
    items.push({ menuItemId: m.id, name: m.name, unitPrice: m.price, quantity });
  }
  return { order, items };
}

app.post('/api/order', writeLimiter, asyncHandler(async (req, res) => {
  const idempotencyKey = str(req.get('Idempotency-Key'));
  if (idempotencyKey.length > 128) return res.status(400).json({ error: 'The idempotency key is too long.' });
  const prepared = await prepareOrder(req.body || {}, { website: true });
  if (prepared.error) return res.status(400).json({ error: prepared.error });
  const { order, items } = prepared;

  const settings = await db.getSettings();
  const notice = Number(settings.min_notice_days) || 0;
  if (order.neededDate < minDateIso(notice)) {
    return res.status(400).json({ error: notice > 0 ? `Please choose a date at least ${notice} day${notice === 1 ? '' : 's'} from today.` : 'Please choose a date from today onwards.' });
  }
  if (order.fulfillment === 'pickup' && !isMarketDay(order.neededDate)) {
    return res.status(400).json({ error: 'Market pickup is on Wednesdays and Saturdays. Please choose one of those days.' });
  }
  if (await db.isDateBlocked(order.neededDate)) {
    return res.status(409).json({ error: 'We are not baking that day. Please choose another date.' });
  }

  const saved = await db.createOrder({ ...order, idempotencyKey: idempotencyKey || null }, items);
  if (saved.duplicate) return res.status(201).json({ ok: true, orderId: saved.id, emailSent: false, duplicate: true });
  const full = await db.getOrder(saved.id);
  const respondUrl = `${BASE_URL}/respond/${saved.id}?token=${saved.respond_token}`;
  const [notice1, thanks] = await Promise.all([
    queueAndDeliver({ orderId: saved.id, kind: 'order_notice', to: mail.ORDERS_INBOX, replyTo: mail.INFO_EMAIL, ...mail.buildBakeryNotice(full, respondUrl) }),
    queueAndDeliver({ orderId: saved.id, kind: 'order_thank_you', to: order.email, replyTo: mail.INFO_EMAIL, ...mail.buildThankYou(full, settings) }),
  ]);
  res.status(201).json({ ok: true, orderId: saved.id, emailSent: thanks.sent && notice1.sent });
}));

app.get('/api/reviews', asyncHandler(async (_req, res) => {
  res.json({ reviews: await db.listApprovedReviews() });
}));

app.post('/api/reviews', writeLimiter, asyncHandler(async (req, res) => {
  const name = str(req.body?.name), review = str(req.body?.review), rating = Number(req.body?.rating);
  if (str(req.body?.website)) return res.status(400).json({ error: 'That review could not be submitted.' });
  if (!name) return res.status(400).json({ error: 'Please tell us your name.' });
  if (!Number.isInteger(rating) || rating < 1 || rating > 5) return res.status(400).json({ error: 'Pick a rating from 1 to 5.' });
  if (!review) return res.status(400).json({ error: 'Please write a few words.' });
  if (review.length > 2000) return res.status(400).json({ error: 'Reviews are limited to 2000 characters.' });
  const saved = await db.createReview({ name, rating, review });
  const notice = await queueAndDeliver({ kind: 'review_notice', to: mail.INFO_EMAIL, replyTo: mail.INFO_EMAIL, ...mail.buildReviewNotice(saved) });
  res.status(201).json({ ok: true, review: { id: saved.id }, emailSent: notice.sent });
}));

// ── respond from the email ───────────────────────────────────────────────
async function respondToOrder(id, action) {
  const order = await db.getOrder(id);
  if (!order) return { status: 404, error: 'Order not found' };
  if (order.status !== 'pending') return { status: 409, error: `This order is already ${order.status}.` };
  if (action === 'accept' && await db.isDateBlocked(db.toIsoDate(order.needed_date))) {
    return { status: 409, error: 'That date is blocked. Unblock it first, or change the date.' };
  }
  return { order: await db.setOrderStatus(id, action === 'accept' ? 'accepted' : 'declined') };
}

function renderRespondPage(order) {
  const e = mail.escapeHtml;
  const head = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Order — ${mail.BAKERY_NAME}</title><link rel="stylesheet" href="/style.css"></head>`;
  if (!order) {
    return `${head}<body style="padding:var(--s16) var(--s5);text-align:center"><h2>Link not valid</h2><p style="opacity:.7">This link is invalid or has expired.</p></body></html>`;
  }
  const done = order.status !== 'pending';
  const items = order.items.map((it) => `<li class="fare" style="justify-content:space-between"><span>${e(it.name)}</span><span>&times; ${it.quantity}</span></li>`).join('');
  return `${head}<body style="padding:var(--s10) var(--s5)">
  <div style="max-width:560px;margin:0 auto;background:var(--paper-2);border:1px solid var(--rule);padding:var(--s8)">
    <p class="caps" style="color:var(--olive)">Order #${order.id}</p>
    <h2 style="font-size:var(--xl);margin-block:var(--s2) var(--s5)">${e(order.first_name)} ${e(order.last_name)}</h2>
    <p><strong>${e(mail.FULFILLMENT_LABELS[order.fulfillment] || order.fulfillment)}</strong><br>${e(mail.formatDate(order.needed_date))}</p>
    ${order.address ? `<p>${e(order.address)}</p>` : ''}
    <ul style="margin-block:var(--s5)">${items}</ul>
    ${order.notes ? `<p style="font-style:italic;opacity:.8">${e(order.notes)}</p>` : ''}
    <p style="font-size:var(--sm);opacity:.7;margin-top:var(--s4)">${e(order.email || '')} ${e(order.phone || '')}</p>
    ${done ? `<p style="margin-top:var(--s6)"><strong>This order is already ${e(order.status)}.</strong></p>`
           : `<div id="respond" data-id="${order.id}" data-token="${e(order.respond_token)}" style="display:flex;gap:var(--s4);margin-top:var(--s6)">
                <button class="btn btn-fill" data-action="accept" style="flex:1">Accept</button>
                <button class="btn btn-line" data-action="decline" style="flex:1">Decline</button></div>
              <p id="respond-msg" style="margin-top:var(--s4);display:none"></p>`}
    <p style="margin-top:var(--s8)"><a href="/admin" class="caps">Open the admin</a></p>
  </div><script src="/respond.js"></script></body></html>`;
}

app.get('/respond/:id', asyncHandler(async (req, res) => {
  const order = await db.getOrder(req.params.id);
  const token = req.query.token;
  if (!order || !token || !safeEqual(token, order.respond_token)) return res.status(404).send(renderRespondPage(null));
  res.send(renderRespondPage(order));
}));

app.post('/api/orders/:id/respond', asyncHandler(async (req, res) => {
  const { action, token } = req.body || {};
  if (!['accept', 'decline'].includes(action)) return res.status(400).json({ error: 'Invalid action' });
  const order = await db.getOrder(req.params.id);
  if (!order || !token || !safeEqual(token, order.respond_token)) return res.status(404).json({ error: 'Order not found' });
  const result = await respondToOrder(req.params.id, action);
  if (result.error) return res.status(result.status).json({ error: result.error });
  res.json({ ok: true, status: result.order.status });
}));

// ── admin API: orders ────────────────────────────────────────────────────
app.get('/api/admin/orders', asyncHandler(async (_req, res) => {
  res.json({ orders: await db.listOrders() });
}));

// Orders taken at the stall, by phone or by message. Nothing is emailed on
// creation — Amanda sends the confirmation when she is ready.
app.post('/api/admin/orders', asyncHandler(async (req, res) => {
  const prepared = await prepareOrder(req.body || {}, { website: false });
  if (prepared.error) return res.status(400).json({ error: prepared.error });
  const saved = await db.createOrder({ ...prepared.order, source: 'manual' }, prepared.items);
  res.status(201).json({ ok: true, order: await db.getOrder(saved.id) });
}));

app.patch('/api/admin/orders/:id', asyncHandler(async (req, res) => {
  const current = await db.getOrder(req.params.id);
  if (!current) return res.status(404).json({ error: 'Order not found' });
  const body = req.body || {};
  const patch = {};
  for (const key of ['firstName', 'lastName', 'email', 'phone', 'fulfillment', 'neededDate', 'address', 'notes']) {
    if (Object.prototype.hasOwnProperty.call(body, key)) patch[key] = body[key];
  }
  if (!Object.keys(patch).length) return res.status(400).json({ error: 'Nothing to change.' });
  const merged = {
    firstName: current.first_name, lastName: current.last_name, email: current.email || '', phone: current.phone || '',
    fulfillment: current.fulfillment, neededDate: db.toIsoDate(current.needed_date), address: current.address || '',
    notes: current.notes || '', ...Object.fromEntries(Object.entries(patch).map(([k, v]) => [k, str(v)])),
  };
  if (!merged.firstName || !merged.lastName) return res.status(400).json({ error: 'First and last name are required.' });
  if (!merged.email && !merged.phone) return res.status(400).json({ error: 'An email address or phone number is required.' });
  if (merged.email && !isEmail(merged.email)) return res.status(400).json({ error: 'That email address does not look right.' });
  if (!FULFILLMENTS.includes(merged.fulfillment)) return res.status(400).json({ error: 'Choose pickup, delivery or shipping.' });
  if (!isIsoDate(merged.neededDate)) return res.status(400).json({ error: 'Date must be a real calendar date.' });
  res.json({ ok: true, order: await db.updateOrder(req.params.id, patch) });
}));

app.post('/api/admin/orders/:id/respond', asyncHandler(async (req, res) => {
  const { action } = req.body || {};
  if (!['accept', 'decline'].includes(action)) return res.status(400).json({ error: 'Invalid action' });
  const result = await respondToOrder(req.params.id, action);
  if (result.error) return res.status(result.status).json({ error: result.error });
  res.json({ ok: true, order: result.order });
}));

app.post('/api/admin/orders/:id/status', asyncHandler(async (req, res) => {
  const { status } = req.body || {};
  if (!ORDER_STATUSES.includes(status)) return res.status(400).json({ error: 'Unknown status.' });
  const order = await db.setOrderStatus(req.params.id, status);
  if (!order) return res.status(404).json({ error: 'Order not found' });
  res.json({ ok: true, order });
}));

app.delete('/api/admin/orders/:id', asyncHandler(async (req, res) => {
  if (!await db.deleteOrder(req.params.id)) return res.status(404).json({ error: 'Order not found' });
  res.json({ ok: true });
}));

app.post('/api/admin/orders/:id/amount', asyncHandler(async (req, res) => {
  const { amount } = req.body || {};
  const parsed = amount === null || amount === '' || amount === undefined ? null : Number(amount);
  if (parsed !== null && (!Number.isFinite(parsed) || parsed < 0)) return res.status(400).json({ error: 'The total must be a number, zero or more.' });
  const current = await db.getOrder(req.params.id);
  if (!current) return res.status(404).json({ error: 'Order not found' });
  if (parsed !== null && Number(current.paid_amount || 0) > parsed) return res.status(400).json({ error: 'The total cannot be lower than what has already been paid.' });
  res.json({ ok: true, order: await db.setOrderAmount(req.params.id, parsed) });
}));

app.post('/api/admin/orders/:id/payments', asyncHandler(async (req, res) => {
  const order = await db.getOrder(req.params.id);
  if (!order) return res.status(404).json({ error: 'Order not found' });
  const { amount, note, receivedAt } = req.body || {};
  const parsed = Number(amount);
  if (!Number.isFinite(parsed) || parsed <= 0) return res.status(400).json({ error: 'Enter how much the customer paid.' });
  if (receivedAt && isNaN(new Date(receivedAt).getTime())) return res.status(400).json({ error: 'That payment date is not a real date.' });
  res.status(201).json({ ok: true, order: await db.addPayment(req.params.id, { amount: parsed, note, receivedAt }) });
}));

app.delete('/api/admin/payments/:paymentId', asyncHandler(async (req, res) => {
  const payment = await db.getPayment(req.params.paymentId);
  if (!payment) return res.status(404).json({ error: 'Payment not found' });
  res.json({ ok: true, order: await db.deletePayment(req.params.paymentId) });
}));

// Status only. The figure comes from the payment log, so there is one place
// to type a number; this is for recording a refund or overriding the log.
app.post('/api/admin/orders/:id/payment', asyncHandler(async (req, res) => {
  const { paymentStatus } = req.body || {};
  if (!PAYMENT_STATUSES.includes(paymentStatus)) return res.status(400).json({ error: 'Payment status is invalid.' });
  const order = await db.setPaymentStatus(req.params.id, paymentStatus);
  if (!order) return res.status(404).json({ error: 'Order not found' });
  res.json({ ok: true, order });
}));

// The three sends. None of them goes out on its own.
async function sendForOrder(req, res, build) {
  const order = await db.getOrder(req.params.id);
  if (!order) return res.status(404).json({ error: 'Order not found' });
  if (!order.email) return res.status(400).json({ error: 'This order has no email address.' });
  if (!mail.configured()) return res.status(503).json({ error: 'Email is not set up yet (RESEND_API_KEY is missing).' });
  const built = await build(order);
  if (built.error) return res.status(400).json({ error: built.error });
  const result = await queueAndDeliver({ orderId: order.id, kind: 'admin_' + built.subject.slice(0, 30), to: order.email, replyTo: mail.INFO_EMAIL, ...built });
  if (!result.sent) return res.status(502).json({ error: `Could not send: ${result.reason}` });
  res.json({ ok: true });
}

app.post('/api/admin/orders/:id/confirmation', asyncHandler((req, res) =>
  sendForOrder(req, res, async (order) => mail.buildConfirmation(order, await db.getSettings()))));

app.post('/api/admin/orders/:id/receipt', asyncHandler((req, res) =>
  sendForOrder(req, res, async (order) => {
    if (!order.payments.length) return { error: 'Record the payment first — none is saved on this order.' };
    const { paymentId } = req.body || {};
    const payment = paymentId ? order.payments.find((p) => String(p.id) === String(paymentId)) : order.payments[0];
    if (!payment) return { error: 'That payment is not on this order.' };
    return mail.buildReceipt(order, payment);
  })));

app.post('/api/admin/orders/:id/email', asyncHandler((req, res) => {
  const subject = str(req.body?.subject), message = str(req.body?.message);
  if (!subject || !message) return res.status(400).json({ error: 'Subject and message are required.' });
  return sendForOrder(req, res, async () => mail.buildPlain(subject, message));
}));

// ── admin API: menu ──────────────────────────────────────────────────────
function menuFields(body, { partial }) {
  const out = {};
  const has = (k) => Object.prototype.hasOwnProperty.call(body, k);
  if (!partial || has('course')) {
    out.course = str(body.course);
    if (!db.COURSES[out.course]) return { error: 'Pick a course for this item.' };
  }
  if (!partial || has('name')) {
    out.name = str(body.name);
    if (!out.name) return { error: 'Give the item a name.' };
    if (out.name.length > 120) return { error: 'Names are limited to 120 characters.' };
  }
  if (has('description')) out.description = str(body.description) || null;
  if (has('price')) {
    const p = body.price === null || body.price === '' ? null : Number(body.price);
    if (p !== null && (!Number.isFinite(p) || p < 0)) return { error: 'Price must be a number, zero or more.' };
    out.price = p;
  }
  if (has('image')) {
    const v = str(body.image).trim();
    // A bare file name from public/img and nothing else. It is written into a
    // src attribute on the order page, so a path or a URL from here must not
    // be able to point it somewhere other than our own images.
    if (!v) out.image = null;
    else if (!/^[A-Za-z0-9][A-Za-z0-9._-]*\.(webp|jpg|jpeg|png)$/.test(v)) {
      return { error: 'Image must be a file name in public/img, like savory-round.webp.' };
    } else out.image = v;
  }
  if (has('available')) out.available = Boolean(body.available);
  if (has('sortOrder')) {
    const n = Number(body.sortOrder);
    if (!Number.isInteger(n)) return { error: 'Sort order must be a whole number.' };
    out.sortOrder = n;
  }
  return { fields: out };
}

app.get('/api/admin/menu', asyncHandler(async (_req, res) => {
  res.json({ courses: db.COURSES, items: await db.listMenu() });
}));
app.post('/api/admin/menu', asyncHandler(async (req, res) => {
  const r = menuFields(req.body || {}, { partial: false });
  if (r.error) return res.status(400).json({ error: r.error });
  res.status(201).json({ ok: true, item: await db.createMenuItem(r.fields) });
}));
app.patch('/api/admin/menu/:id', asyncHandler(async (req, res) => {
  const r = menuFields(req.body || {}, { partial: true });
  if (r.error) return res.status(400).json({ error: r.error });
  const item = await db.updateMenuItem(req.params.id, r.fields);
  if (!item) return res.status(404).json({ error: 'Item not found' });
  res.json({ ok: true, item });
}));
app.delete('/api/admin/menu/:id', asyncHandler(async (req, res) => {
  if (!await db.deleteMenuItem(req.params.id)) return res.status(404).json({ error: 'Item not found' });
  res.json({ ok: true });
}));

// ── admin API: blocks, customers, reviews, settings, password ────────────
app.get('/api/admin/blocks', asyncHandler(async (_req, res) => res.json({ blocks: await db.listBlocks() })));
app.post('/api/admin/blocks', asyncHandler(async (req, res) => {
  const { startDate, endDate, reason } = req.body || {};
  if (!isIsoDate(startDate) || !isIsoDate(endDate)) return res.status(400).json({ error: 'Start and end dates are required.' });
  if (endDate < startDate) return res.status(400).json({ error: 'The end date must be on or after the start date.' });
  res.status(201).json({ ok: true, block: await db.createBlock({ startDate, endDate, reason: str(reason) }) });
}));
app.delete('/api/admin/blocks/:id', asyncHandler(async (req, res) => { await db.deleteBlock(req.params.id); res.json({ ok: true }); }));

app.get('/api/admin/customers', asyncHandler(async (_req, res) => res.json({ customers: await db.getCustomers() })));
app.delete('/api/admin/customers/:key', asyncHandler(async (req, res) => { await db.deleteCustomer(req.params.key); res.json({ ok: true }); }));

app.get('/api/admin/reviews', asyncHandler(async (_req, res) => res.json({ reviews: await db.listAllReviews() })));
app.post('/api/admin/reviews/:id/approve', asyncHandler(async (req, res) => {
  const r = await db.setReviewStatus(req.params.id, 'approved');
  if (!r) return res.status(404).json({ error: 'Review not found' });
  res.json({ ok: true, review: r });
}));
app.post('/api/admin/reviews/:id/reject', asyncHandler(async (req, res) => {
  const r = await db.setReviewStatus(req.params.id, 'rejected');
  if (!r) return res.status(404).json({ error: 'Review not found' });
  res.json({ ok: true, review: r });
}));
app.delete('/api/admin/reviews/:id', asyncHandler(async (req, res) => { await db.deleteReview(req.params.id); res.json({ ok: true }); }));

app.get('/api/admin/settings', asyncHandler(async (_req, res) => res.json({ settings: await db.getSettings(), emailConfigured: mail.configured(), emailOutbox: await db.emailOutboxSummary() })));
app.post('/api/admin/email-outbox/retry', asyncHandler(async (_req, res) => {
  const count = await db.retryFailedEmails();
  await processEmailOutbox();
  res.json({ ok: true, retried: count, emailOutbox: await db.emailOutboxSummary() });
}));
app.put('/api/admin/settings', asyncHandler(async (req, res) => {
  const body = req.body || {};
  const patch = {};
  if ('deposit_percent' in body) {
    const n = Number(body.deposit_percent);
    if (!Number.isInteger(n) || n < 0 || n > 100) return res.status(400).json({ error: 'Deposit must be a whole percentage from 0 to 100.' });
    patch.deposit_percent = String(n);
  }
  if ('min_notice_days' in body) {
    const n = Number(body.min_notice_days);
    if (!Number.isInteger(n) || n < 0 || n > 60) return res.status(400).json({ error: 'Notice must be a whole number of days, 0 to 60.' });
    patch.min_notice_days = String(n);
  }
  for (const key of ['payment_instructions', 'pickup_note']) {
    if (!(key in body)) continue;
    const v = str(body[key]);
    if (!v) return res.status(400).json({ error: 'That text cannot be empty.' });
    if (v.length > 1000) return res.status(400).json({ error: 'That text is limited to 1000 characters.' });
    patch[key] = v;
  }
  res.json({ ok: true, settings: await db.setSettings(patch) });
}));

app.post('/api/admin/password', asyncHandler(async (req, res) => {
  const { currentPassword, newPassword } = req.body || {};
  if (!currentPassword || !newPassword || String(newPassword).length < 8) {
    return res.status(400).json({ error: 'Enter the current password and a new one of at least 8 characters.' });
  }
  const creds = await db.getAdminCredentials();
  if (!creds || !verifyPassword(currentPassword, creds.password_hash)) return res.status(401).json({ error: 'The current password is incorrect.' });
  await db.setAdminCredentials(creds.username, hashPassword(newPassword));
  res.json({ ok: true });
}));

// ── static site ──────────────────────────────────────────────────────────
app.use(express.static(PUBLIC_DIR, {
  extensions: ['html'],
  setHeaders(res, filePath) {
    res.setHeader('Cache-Control', /\.(webp|jpg|png|svg|ico)$/.test(filePath)
      ? 'public, max-age=31536000, immutable'
      : 'public, max-age=300');
  },
}));

app.use((req, res) => {
  if (req.path.startsWith('/api/')) return res.status(404).json({ error: 'Not found' });
  res.status(404).sendFile(path.join(PUBLIC_DIR, '404.html'));
});

app.use((err, _req, res, next) => {
  console.error('Unhandled server error:', err);
  if (res.headersSent) return next(err);
  if (_req.path.startsWith('/api/') || _req.path.startsWith('/admin/')) return res.status(500).json({ error: 'Something went wrong on our side.' });
  res.status(500).send('Something went wrong on our side.');
});

if (require.main === module) {
  const start = () => {
    app.listen(PORT, () => console.log(`Oh! You Fancy Focaccia listening on ${PORT}`));
    if (process.env.DATABASE_URL) {
      processEmailOutbox().catch((err) => console.error('Email outbox startup sweep failed:', err));
      const timer = setInterval(() => processEmailOutbox().catch((err) => console.error('Email outbox sweep failed:', err)), 60_000);
      timer.unref();
    }
  };
  if (process.env.DATABASE_URL) {
    db.initSchema().then(start).catch((err) => {
      console.error('Failed to initialise the database:', err);
      process.exit(1);
    });
  } else {
    console.warn('DATABASE_URL is not set — serving the site without ordering or the admin.');
    start();
  }
}

module.exports = app;
module.exports.resolveBaseUrl = resolveBaseUrl;
