// Oh! You Fancy Focaccia — static site server.
// Everything under public/ is generated by `npm run build` (site/build_site.py).
const path = require('path');
const express = require('express');
const helmet = require('helmet');
const compression = require('compression');

const app = express();
const PORT = process.env.PORT || 3000;
const PUBLIC_DIR = path.join(__dirname, 'public');

app.disable('x-powered-by');
app.set('trust proxy', 1);

// The design leans on inline style attributes throughout, so style-src has to
// allow them; scripts do not, which is why the splash lives in its own file.
app.use(helmet({
  contentSecurityPolicy: {
    directives: {
      defaultSrc: ["'self'"],
      scriptSrc: ["'self'"],
      styleSrc: ["'self'", "'unsafe-inline'", 'https://fonts.googleapis.com'],
      fontSrc: ["'self'", 'https://fonts.gstatic.com'],
      imgSrc: ["'self'", 'data:'],
      connectSrc: ["'self'"],
      formAction: ["'self'"],
      frameAncestors: ["'none'"],
      objectSrc: ["'none'"],
      baseUri: ["'self'"],
      upgradeInsecureRequests: [],
    },
  },
  crossOriginEmbedderPolicy: false,
  referrerPolicy: { policy: 'strict-origin-when-cross-origin' },
}));
app.use(compression());

// Send every hostname to one canonical host, so www and the apex do not both
// get indexed. Off unless CANONICAL_HOST is set — enabling it before the apex
// DNS record exists would redirect the only working hostname into a dead one.
const CANONICAL_HOST = process.env.CANONICAL_HOST;
if (CANONICAL_HOST) {
  app.use((req, res, next) => {
    const host = (req.headers.host || '').toLowerCase().split(':')[0];
    if (host && host !== CANONICAL_HOST && !host.endsWith('.up.railway.app')) {
      return res.redirect(308, `https://${CANONICAL_HOST}${req.originalUrl}`);
    }
    next();
  });
}

app.get('/healthz', (_req, res) => res.status(200).send('ok'));

app.use(express.static(PUBLIC_DIR, {
  extensions: ['html'],
  setHeaders(res, filePath) {
    // fingerprint-free filenames, so hold HTML short and let assets sit
    res.setHeader('Cache-Control', /\.(webp|jpg|png|svg|ico)$/.test(filePath)
      ? 'public, max-age=31536000, immutable'
      : 'public, max-age=300');
  },
}));

app.use((_req, res) => {
  res.status(404).sendFile(path.join(PUBLIC_DIR, 'index.html'));
});

if (require.main === module) {
  app.listen(PORT, () => console.log(`Oh! You Fancy Focaccia listening on ${PORT}`));
}

module.exports = app;
